satnaing/shadcn-admin

src/components/custom/breadcrumb.tsx
src/components/custom/pin-input-2.tsx
src/components/custom/pin-input.tsx
src/data/sidelinks.tsx
src/pages/extra-components/index.tsx
src/router.tsx

- when a character is typed in an input, shift focus to the next input
- when a character is deleted from an input, shift focus to the previous input
- when a focus is set in an input, placeholder is removed
- each input only allows one character at a time
- user can navigate through each digit input using the keyboard (Tab key, arrow keys, back button)
- user can paste the copied code into every input field
- validate the input based on the type_ only numbers allowed if `type='number'`, and other characters ([a-zA-Z0-9]) allowed if `type='alphanumeric'`
- provide visual masking for each digit entered to enhance privacy
- support both controlled and uncontrolled behaviors

feat: implement custom pin-input component

---

src/components/custom/layout.tsx
src/components/sidebar.tsx
src/index.css
src/pages/apps/index.tsx
src/pages/dashboard/index.tsx
src/pages/extra-components/index.tsx
src/pages/settings/account/index.tsx
src/pages/settings/appearance/index.tsx
src/pages/settings/components/content-section.tsx
src/pages/settings/display/index.tsx
src/pages/settings/index.tsx
src/pages/settings/notifications/index.tsx
src/pages/settings/profile/index.tsx
src/pages/tasks/index.tsx

Changes made
- update main and sidebar layouts
- solve overflow issues in mobile sidebar menu
- extract repetitive codes into a reusable component
- hide unnecessary overflow

fix: update layouts and solve overflow issues

---

.eslintrc.cjs
package.json
pnpm-lock.yaml

Changes made:
- update eslint script.
- exclude `tailwind.config.js` from linting.

fix: resolve eslint script issue

---

pnpm-lock.yaml
src/components/custom/search-input.tsx
src/data/conversations.json
src/hooks/use-previous.tsx
src/pages/chats/index.tsx
src/router.tsx

feat: implement chat page

---

src/components/app-shell.tsx
src/components/skip-to-main.tsx

feat: add "skip to main" button

---

src/components/theme-switch.tsx

Theme button is upgraded to theme dropdown to include system as an option.
Resolves #29

feat: upgrade theme button to theme dropdown

---

src/components/theme-provider.tsx

fix: tweaking theme provider

---

src/components/layout/nav-user.tsx
src/components/profile-dropdown.tsx

Currently no action perform on click on profile dropdown

feat: navigation link added in profile dropdown

---

src/index.css

fix(style): update global scrollbar style

---

tailwind.config.js

[for issues/96](https://github.com/satnaing/shadcn-admin/issues/96)
I had the same problem, use AI check code and fix this issue, it works for me
Closes: #96

fix issues/96

---

package.json
pnpm-lock.yaml
src/components/ui/calendar.tsx

Upgrade react-day-picker to v9.6.6 and update calendar component accordingly.

fix: upgrade react-day-picker and update calendar component

---

src/routes/_authenticated/route.tsx

| Before | After |
| -- | -- |
|  <video src="https://github.com/user-attachments/assets/8480fd41-6de0-4496-9a63-b1bd3548b312"> | <video src="https://github.com/user-attachments/assets/32c3aa2f-d6bc-4be4-b488-72319da2b132"> |

fix: disable layout animation on mobile

---

src/components/layout/nav-group.tsx

fix: prevent showing collapsed menu on mobile

---

package.json
pnpm-lock.yaml

Remove unused next-themes dependency

chore: remove unused next-themes dependency

---

src/components/search.tsx
src/components/ui/sidebar.tsx
src/features/auth/auth-layout.tsx
src/features/chats/components/new-chat.tsx
src/features/chats/index.tsx
src/features/settings/components/sidebar-nav.tsx

fix: update hard-coded or inconsistent colors

---

src/components/layout/data/sidebar-data.ts
src/components/layout/types.ts
src/routeTree.gen.ts
src/routes/_authenticated/errors/$error.tsx

Display error pages inside the dashboard instead of redirecting to route pages.
https://github.com/user-attachments/assets/ba6004c9-cd56-40a1-895c-540aa31c3542

refactor: update error routes

---

src/features/users/components/data-table-column-header.tsx
src/features/users/components/users-columns.tsx
src/features/users/components/users-table.tsx

Improved hover and selected styles in user table using container queries.
https://github.com/user-attachments/assets/6a0e825f-2491-4a78-8d51-d039101763c5

fix: improve user table hover & selected styles

---

src/features/apps/index.tsx
src/routes/_authenticated/apps/index.tsx

Sync app route states with search param
Closes #184

feat: add search param sync in apps route

---

src/assets/logo.tsx
src/features/auth/auth-layout.tsx
src/features/auth/sign-in/sign-in-2.tsx
src/routes/clerk/(auth)/route.tsx

refactor: replace inline svg logo with logo component

---

src/components/data-table/pagination.tsx

fix: pagination button spacing
