satnaing/shadcn-admin

src/data/sidelinks.tsx, src/pages/errors/unauthorised-error.tsx, src/router.tsx
this PR implements a 401 Unauthorized error page for the admin panel using Shadcn UI. When a user attempts to directly access a URL without the necessary permissions, they will be redirected to this page.
**Changes Made:**
Added a 401 Unauthorized error page template.
Updated routing logic to redirect unauthorized access to the 401 page.
=> page 401 added

src/index.css
Set font-size to 16px for input, select, and
textarea elements on mobile screens to prevent
zooming when focused.
=> fix: prevent focus zoom on mobile devices

src/components/custom/button.tsx
Update Button component to accept both `asChild` and custom properties.
=> fix: improve custom Button component

src/components/custom/pin-input.tsx
Ensure onComplete is invoked only once when the
pin input is fully completed. Invoke onIncomplete
only once when the pin input changes from complete to incomplete.
=> fix: optimize onComplete/onIncomplete invocation

src/components/layout/nav-group.tsx, src/components/layout/types.ts
https://github.com/user-attachments/assets/061604e6-0644-413e-98dc-f423ae7b0896
=> fix: display menu dropdown when sidebar collapsed

vite.config.ts
Unnecessary tabler icon chunks are loaded in dev
mode which causes the performance issue during development. This issue is solved by replacing the import alias for '@tabler/icons-react' in vite.config.ts
Resolves #54
=> fix: loading all tabler-icon chunks in dev mode

index.html, src/components/layout/header.tsx, src/components/layout/main.tsx, src/features/tasks/index.tsx, src/features/users/index.tsx, src/routes/_authenticated/route.tsx
https://github.com/user-attachments/assets/6f8149a7-06df-44c9-b950-5261b1f6b079
Resolves #65
=> fix: update overall layout due to scroll-lock bug

src/features/tasks/components/tasks-import-dialog.tsx
=> fix: add gap between buttons in import task dialog

src/features/tasks/components/data-table-row-actions.tsx, src/features/tasks/components/tasks-dialogs.tsx, src/features/tasks/components/tasks-primary-buttons.tsx, src/features/tasks/context/tasks-context.tsx, src/features/tasks/index.tsx, src/features/users/components/data-table-row-actions.tsx, src/features/users/components/users-dialogs.tsx, src/features/users/components/users-primary-buttons.tsx, src/features/users/context/users-context.tsx, src/features/users/index.tsx
Although the changes don't significantly improve performance (because of how states are used in this case), this PR will make it easier for users to migrate to RSC in the future.
- (`TasksContextProvider` => `TasksProvider`, `useTasksContext` => `useTasks`)
- (`TasksContext.Provider` => `TasksContext`, `UsersContext.Provider` => `UsersContext`)
=> Refactor/optimize context & states

src/features/users/components/data-table-toolbar.tsx
This pull request updates the placeholder text in the data-table-toolbar.tsx file for the user table. The placeholder has been changed from `Filter tasks...` to `Filter users...` to ensure clarity and better context for filtering user-related data.
This change is straightforward and focuses on improving the user interface for the user table.
Closes: #
=> fix: toolbar filter placeholder typo in user table

src/index.css
I apologize before, I think the sidebar color for dark mode doesn't have the same style as the overall (dark mode) design, color, and look & feel, for light mode I think it still fits, but for dark mode it's like a different design
Before :
After :
=> fix: update sidebar color in dark mode for consistent look

.prettierrc, src/components/layout/header.tsx, src/components/layout/main.tsx, src/components/layout/nav-group.tsx, src/components/search.tsx, src/components/ui/command.tsx, src/components/ui/dialog.tsx, src/components/ui/dropdown-menu.tsx, src/components/ui/sheet.tsx, src/components/ui/sidebar.tsx, src/features/chats/index.tsx, src/features/settings/components/content-section.tsx, src/features/settings/components/sidebar-nav.tsx, src/features/settings/index.tsx, src/features/settings/notifications/notifications-form.tsx, src/features/tasks/components/tasks-import-dialog.tsx, src/features/tasks/components/tasks-mutate-drawer.tsx, src/features/tasks/index.tsx, src/features/users/components/users-action-dialog.tsx, src/features/users/components/users-columns.tsx, src/features/users/index.tsx, src/routes/_authenticated/route.tsx
Somehow, `prettier-plugin-tailwindcss` doesn't work if we put that in the first index of plugins inside `.prettierrc`.
This PR fixes that and update formatting as well.
=> chore: update prettier-plugin-tailwindcss order

eslint.config.js, src/components/create-conversation-dialog.tsx, src/features/chats/components/new-chat.tsx, src/features/chats/data/chat-types.ts, src/features/chats/index.tsx
Implements a "new message creation" feature in the chat interface that allows users to initiate new conversations directly from the inbox page. This PR adds a modal-based interface for searching and selecting message recipients, improving the overall user experience by eliminating the need to navigate away from the main chat view.
[Screencast from 2025-01-31 12-28-41.webm](https://github.com/user-attachments/assets/f01ee56c-06f7-43d2-b4db-cc219ee1d64d)
Closes: #89
=> feat: add new chat dialog in chats page

src/features/users/components/users-action-dialog.tsx
Focus inside add user dialog is broken. Second input field should be focused after the first input. Instead modal dialog is focused. This is fixed by removing scroll-area with vertical scrollable div element.
Resolves #100
=> fix: broken focus behavior in add user dialog

package.json, pnpm-lock.yaml, src/components/navigation-progress.tsx, src/routes/__root.tsx
This PR implements a loading indicator that appears during route transitions, addressing #81.
Changes Made:
- Integrated a loading top progress bar ([react-top-loading-bar](https://www.npmjs.com/package/react-top-loading-bar)) that shows when navigating between pages.
- Used `useRouterState` to detect loading states.
Why This Is Useful:
- Improves user experience by giving feedback during page transitions.
- Makes the admin interface feel more responsive and polished.
Let me know if there's anything else you'd like me to tweak or improve!
Closes: #81
=> feat: add loading indicator during page transitions

src/features/settings/components/content-section.tsx, src/index.css
Replace hard-coded color with css variable in faded-bottom utility class. 
Fix broken faded style in setting content.
Closes #134
=> fix: update faded-bottom color with css variable

src/features/tasks/components/data-table.tsx, src/features/users/components/users-table.tsx
Hide overflow background colors when the table is hovered, or one/more rows are selected.
| Before | After |
| --- | --- |
| <img width="2160" height="1350" alt="image" src="https://github.com/user-attachments/assets/91e94ab5-6d0d-4159-838a-ba3f54ee47d9" /> | <img width="2160" height="1350" alt="image" src="https://github.com/user-attachments/assets/211bffc6-2f33-4d4b-b21f-4806a2d6bf90" /> |
=> fix: overflow background in tables

src/components/layout/authenticated-layout.tsx, src/components/layout/main.tsx
Added max-width for large screens
=> fix: add max-width for large screens to improve responsiveness

src/components/bulk-actions-toolbar.tsx, src/features/tasks/components/data-table-bulk-actions.tsx, src/features/tasks/components/data-table.tsx, src/features/tasks/components/tasks-multi-delete-dialog.tsx, src/features/users/components/data-table-bulk-actions.tsx, src/features/users/components/users-multi-delete-dialog.tsx, src/features/users/components/users-table.tsx
This commit introduces a new bulk action toolbar that appears when a user selects one or more rows in a data table, providing an intuitive way to perform actions on multiple items at once.
The new `BulkActionsToolbar` is a generic and reusable component designed with accessibility in mind. It features full keyboard navigation (Arrow keys, Home, End, Escape) and provides ARIA live announcements for screen readers.
Key features include:
- A floating design that remains fixed at the bottom of the viewport.
- Bulk actions for the Tasks table: update status, change priority, export, and delete.
- Bulk actions for the Users table: invite, activate/deactivate, and delete.
- A confirmation dialog for destructive actions, requiring the user to type "DELETE" to proceed. …
=> feat: add data table bulk action toolbar

package.json, pnpm-lock.yaml
addresses lucide-icons/lucide#3571
While launching the dev and build commands, Windows' native antivirus treats a file from the `lucide-react` package as a Trojan.
I looked it up and saw that this has [already been solved](https://github.com/lucide-icons/lucide/issues/3571#issuecomment-3216684301) by the package maintainer.
The linked issue explains it all but here's an additional screenshot:
References: lucide-icons/lucide#3571
=> Upgrade lucide-react so Microsoft Defender doesn't quarantine it

src/components/layout/app-sidebar.tsx, src/components/layout/app-title.tsx
https://github.com/user-attachments/assets/0f745fdc-1435-4a74-bf84-8a74ec8d523f
=> feat: add extra AppTitle component for sidebar header
